In [61]:
from pydrake.all import (
    AddMultibodyPlantSceneGraph, DiagramBuilder, 
    FindResourceOrThrow, GenerateHtml, InverseDynamicsController, 
    MultibodyPlant, Parser, Simulator)
from pydrake.multibody.jupyter_widgets import MakeJointSlidersThatPublishOnCallback
import pydrake
from pydrake import geometry
from pydrake.math import RigidTransform, RollPitchYaw, RotationMatrix 
from pydrake.solvers import MathematicalProgram, Solve
from pydrake.systems.jupyter_widgets import PoseSliders, WidgetSystem
from ipywidgets import ToggleButton, ToggleButtons
from functools import partial
from pydrake.all import (
    JointIndex, PiecewisePolynomial, JacobianWrtVariable,
    eq, ge,  AutoDiffXd, SnoptSolver, IpoptSolver,  
    AddUnitQuaternionConstraintOnPlant, PositionConstraint, OrientationConstraint
    )
import numpy as np

In [73]:
prog = MathematicalProgram()
var1 = prog.NewContinuousVariables(3, 10, "q")
var2 = prog.NewContinuousVariables(4, 10, "v")
var3 = prog.NewContinuousVariables(4, 1, "var3")
var4 = prog.NewContinuousVariables(4, "var4")
var4.shape

(4,)

In [63]:
combined = np.vstack((var1, var2))

In [83]:
combined.shape
isinstance(var1[0,0], AutoDiffXd)

False

In [66]:
dir(prog)

['Add2NormSquaredCost',
 'AddBoundingBoxConstraint',
 'AddConstraint',
 'AddCost',
 'AddDecisionVariables',
 'AddEqualityConstraintBetweenPolynomials',
 'AddExponentialConeConstraint',
 'AddIndeterminate',
 'AddIndeterminates',
 'AddL2NormCost',
 'AddL2NormCostUsingConicConstraint',
 'AddLinearComplementarityConstraint',
 'AddLinearConstraint',
 'AddLinearCost',
 'AddLinearEqualityConstraint',
 'AddLinearMatrixInequalityConstraint',
 'AddLorentzConeConstraint',
 'AddMaximizeGeometricMeanCost',
 'AddMaximizeLogDeterminantCost',
 'AddPositiveDiagonallyDominantMatrixConstraint',
 'AddPositiveSemidefiniteConstraint',
 'AddQuadraticAsRotatedLorentzConeConstraint',
 'AddQuadraticConstraint',
 'AddQuadraticCost',
 'AddQuadraticErrorCost',
 'AddRotatedLorentzConeConstraint',
 'AddScaledDiagonallyDominantMatrixConstraint',
 'AddSosConstraint',
 'AddVisualizationCallback',
 'CheckSatisfied',
 'CheckSatisfiedAtInitialGuess',
 'ClearVariableScaling',
 'Clone',
 'EvalBinding',
 'EvalBindingAtInitia

# Testing decVar indexing

In [1]:
import numpy as np

In [14]:
row = np.linspace(1, 10, 10)

In [16]:
row

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
test = np.repeat([row], 7, axis=0)

In [26]:
test

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [58]:
nTime = 100
ndecVar = (13 + 13 + 7 + 5*(6+1+1)) * nTime
ndecVar

7300

In [59]:
index = np.array([i for i in range(ndecVar)])

In [60]:
index

array([   0,    1,    2, ..., 7297, 7298, 7299])

In [80]:
row[-3:]

array([ 8.,  9., 10.])

In [82]:
row.reshape((2,5), order='F')

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

In [84]:
row

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
row[:3]

array([1., 2., 3.])

In [87]:
row[3:7]

array([4., 5., 6., 7.])

In [89]:
np.split(row, [3,6])

[array([1., 2., 3.]), array([4., 5., 6.]), array([ 7.,  8.,  9., 10.])]

In [90]:
from functools import partial

poke1 = 5

# A normal function
def f(a, b, c, x):
    return 1000*a + 100*b + 10*c + x
 
# A partial function that calls f with
# a as 3, b as 1 and c as 4.
g = partial(f, poke1, 1, 4)

In [92]:
g(5)

5145

In [94]:
row = np.linspace(1, 10, 10)
col = np.linspace(1, 10, 10)

for i, (r, c) in enumerate(zip(row, col)):
    print(i, r, c)

0 1.0 1.0
1 2.0 2.0
2 3.0 3.0
3 4.0 4.0
4 5.0 5.0
5 6.0 6.0
6 7.0 7.0
7 8.0 8.0
8 9.0 9.0
9 10.0 10.0


In [95]:
row[4:]

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [96]:
row

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [98]:
row[4:][3:]

array([ 8.,  9., 10.])